version:0.2

phases:
  build:
    commands:
      - echo Entered the build phase...
      - mvn clean package
  post build:
    commands:
      - echo Build completed successfully
artifacts:
  files:
    -target/order-service.jar
  dicard paths: yes
